#!/usr/bin/env python3
import subprocess

JSON = {
    "text": "...",
    "tooltip": "Not running",
}

def printjson(json : dict):
    print("{", end='')
    count = 0
    for key in json.keys():
        if count > 0:
            print(',', end='')
        print("\"" + key + "\":", end='')
        print("\"" + json[key] + "\"",end='')
        count += 1
    print("}",end='')

def rebuild_string_with_correct_naming_and_such_idk_this_is_just_so_that_waybar_doesnt_shit_itself(name) -> str:
    result = ""

    if name == "No players found":
        printjson(JSON)
        exit(0)

    for i in name:
        if i == "\"":
            result += "\\\""
        elif i == "\\":
            result += "\\\\"
        elif i == "":
            result += "\\+"
        else:
            result += i

    return result

cleanup = rebuild_string_with_correct_naming_and_such_idk_this_is_just_so_that_waybar_doesnt_shit_itself

STATUS = cleanup(subprocess.getoutput("playerctl --player=spotify status"))
TITLE  = cleanup(subprocess.getoutput("playerctl --player=spotify metadata title"))
ARTIST = cleanup(subprocess.getoutput("playerctl --player=spotify metadata artist"))
ALBUM  = cleanup(subprocess.getoutput("playerctl --player=spotify metadata album"))
VOLUME = int(round(float(cleanup(subprocess.getoutput("playerctl --player=spotify metadata --format \"{{ volume }}\""))) * 100, 0))

JSON["text"]    = f"{STATUS}: {TITLE} - {ARTIST}"
JSON["tooltip"] = f"Title: {TITLE}\\nArtist: {ARTIST}\\nAlbum: {ALBUM}\\nVolume: {VOLUME}%"

printjson(JSON)
print("")
